# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Suppress compileSdk compatibility warning
android.suppressUnsupportedCompileSdk=35
